# .streamlit/secrets.toml

# Everything in this section will be available as an environment variable
db_username = "root"
db_password = "qTi5zejHl22POl6ZkUTa"

# You can also add other sections if you like.
# The contents of sections as shown below will not become environment variables,
# but they'll be easily accessible from within Streamlit anyway as we show
# later in this doc.
# [my_cool_secrets]
# things_i_like = ["Streamlit", "Python"]

[connections.mysql]
dialect = "mysql"
host = "containers-us-west-64.railway.app"
port = 7086
database = "railway"
username = "root"
password = "qTi5zejHl22POl6ZkUTa"
secret = "1234